### ISSUE TITLE
YAML support

### ISSUE THREAD

**Issue by ysangkok** [taimoorzaeem/aeson-jsonpath#3]
It would be nice to use JSONPath on YAML files that contain comments.

That way, you could e.g. extract and patch dependencies in `stack.yaml` files.

**Comment by taimoorzaeem** [comment]
The [RFC](https://www.rfc-editor.org/rfc/rfc9535) does not say anything related to YAML and there is no official specification related to querying YAML documents as yet. IMO, a dedicated package for YAML would be much more maintainable, something like [yamlpath](https://pypi.org/project/yamlpath/) in python.

**Comment by ysangkok** [comment]
All right, should I close this then?
